### ISSUE TITLE
Empty table when multiple parents and mode register

### ISSUE THREAD

**Issue by dominikpeter** [fabricks-framework/fabricks#11]
The following constellation results in an empty table in "silver":

Bronze:
```yml
- job:
    step: staging
    topic: erp
    item: xy_linktable
    options:
      mode: register
      keys: [id]
      source: xy
      parser: delta
      uri: abfss://azure/xy
    invoker_options:
      pre_run:
        notebook: extractors/sql_server/extract_table
        arguments:
          db: prod
          schema: dbo
          table: XY$LinkTable
          system: erp
          
- job:
    step: staging
    topic: erp
    item: xx_linktable
    options:
      mode: register
      keys: [id]
      source: xx
      parser: delta
      uri: abfss://azure/xx
    invoker_options:
      pre_run:
        notebook: extractors/sql_server/extract_table
        arguments:
          db: prod
          schema: dbo
          table: XX$LinkTable
          system: erp
```

Silver:
```yml
- job:
    step: silver
    topic: erp
    item: linktable
    options:
      mode: update
      change_data_capture: scd1
      parents:
        - bronze.erp_xy_linktable
        - bronze.erp_xx_linktable
```
