### ISSUE TITLE
Copy-On-Write for testing

### ISSUE THREAD

**Issue by aersam** [fabricks-framework/fabricks#52]
While one can use a completely different data for prod and test, it's often not really an option to have a full dedicated test env. It can cost a lot and also you're pretty likely to just not use it because data is outdated. So best would be to have an option to run tests on kind-of a copy from prod. 

So here's my proposal:

- for each step, allow a new path_option that's called something like `copy_from_storage`:
  
```yml


        path_options:
          runtime: gold/transf
          storage: abfss://gold@$standard.dfs.core.windows.net/transf_test
          copy_from_storage: abfss://gold@$standard.dfs.core.windows.net/transf
```

- Then, if you do a `run`/`truncate`, and the target delta table does not exist already, you create a `SHALLOW CLONE` from the production table. If you do drop, you don't, but instead delete the cloned version if it exists. This does imply there is a drop_create command on the job, that will not do Shallow clone at all (since you want a new table then)

It's then up to the user to regularly delete the test storage data again, as the underlying data of the Shallow clone could be outdated
