### ISSUE TITLE
FABRICKS_RUNTIME and FABRICKS_NOTEBOOKS issues

### ISSUE THREAD

**Issue by aersam** [fabricks-framework/fabricks#67]
If multiple users share the same cluster and have different copies of a Fabricks Runtime, the FABRICKS_RUNTIME and FABRICKS_NOTEBOOKS  env vars will make trouble. To create a cluster per user is costly. 

There are multiple possible solutions:

- One could pass along the runtime/notebooks path using setTaskValues
- Try to get the paths automatically based on some config. Python would be to walk up the tree until you reach a `pyproject.toml` with something like this:
```toml
[tool.fabricks]
notebook_path = "fabricks/notebooks"
runtime_path = "."
```

What do you think?
